export const handleResponsiveness=(xs,md)=>{
  return {xs:xs,md:md}
}

export const signUpStyle={
  signUpMainContainer:{
    width:'100%',
    height:handleResponsiveness('auto','100vh'),
    display:'flex',
    flexDirection:handleResponsiveness('column-reverse','row-reverse'),
  },
  signUpLeftContainer:{
    width:handleResponsiveness('100%','50%'),
    height:handleResponsiveness('auto','100%'),
    backgroundColor:'white',
    borderRadius:'0',
    overflowY:{md:'scroll',xs:'hidden'},
    overflowX:'hidden'
  },
  companyLogo:{
    width:handleResponsiveness('70%','50%'),
    height:handleResponsiveness('30%','50%'),
    display:'flex',
    justifyContent:'space-between',
    alignItems:'center',
    padding:'20px',
    cursor:'pinter',
    position:'absolute',
    zIndex:400,
    marginTop:handleResponsiveness('-500px','-340px')
  },

  signUpCardContainer:{
    width:'100%',
    height:handleResponsiveness('auto','80vh'),
    display:'flex',
    justifyContent:'center',
  
  },
  signUpCard:{
    width:'450px',
    height:'700px',
    boxShadow:'none',
 
  },
  signUpTitleContainer:{
    width:'100%',
    height:'50px',
    display:'flex',
    justifyContent:'center',
    alignItems:'center',
    marginTop:{xs:'20px',md:'0px'}
  },
  signUpInputFieldContainer:{
    width:'100%',
    height:'50px',
    display:'flex',
    justifyContent:'center',
    alignItems:'center',
    marginTop:'20px'
  },
  signUpGenderContainer:{
    width:'80%',
    height:'50px',
    display:'flex',
    justifyContent:'flex-start',
    alignItems:'center',
    marginTop:'40px',
    marginLeft:'10%'
  },
  signUpNameInputFieldContainer:{
    width:'80%',
    height:'50px',
    display:'flex',
    marginLeft:'10%',
    justifyContent:'center',
    alignItems:'center',
    marginTop:'20px'
  },
  signUpButtonContainer:{
    width:'96%',
    height:'50px',
    display:'flex',
    justifyContent:'center',
    alignItems:'center',
    marginTop:'30px',
  },
  forgotPasswordContainer:{
    width:'77%',
    height:'30px',
    marginTop:'16px',
    display:'flex',
    justifyContent:'flex-end',
    alignItems:'center',
    marginLeft:'10%'
  },
  signUpRightContainer:{
    width:handleResponsiveness('100%','50%'),
    height:handleResponsiveness('auto','100%'),
    backgroundColor:'#D9D9D9',
    borderRadius:'0'
  },
  companyName:{
      width:'100%',
      height:'80px',
      display:{xs:'none',md:'flex'},
      justifyContent:'flex-end',
      alignItems:'center',
  },
  createAccountLabelContainer:{
      width:'100%',
      height:'40px',
      display:'flex',
      justifyContent:'center',
      marginTop:'10px'
  }
}
